# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
   config.vm.define :centos_server do |nodoServer|
    nodoServer.vm.box = "centos_rabbit"
    nodoServer.vm.network :private_network, ip: "192.168.56.61"
    nodoServer.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1024","--cpus", "1", "--name", "centos_services" ]
    end
    nodoServer.vm.provision "shell", path: "nodoServer.sh"
  end
  
  config.vm.define :centos_serviceA1 do |nodoServiceA1|
    nodoServiceA1.vm.box = "centos_rabbit"
    nodoServiceA1.vm.network :private_network, ip: "192.168.56.62"
    nodoServiceA1.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "256","--cpus", "1", "--name", "centos_serviceA1" ]
    end
    nodoServiceA1.vm.provision "shell", path: "serviceA.sh"
  end
  
  config.vm.define :centos_balanceador do |balanceador|
    balanceador.vm.box = "centos_rabbit"
    balanceador.vm.network :private_network, ip: "192.168.56.63"
    balanceador.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "256","--cpus", "1", "--name", "centos_balanceador" ]
    end
    balanceador.vm.provision "shell", path: "balanceador.sh"
  end
  
  config.vm.define :centos_serviceA2 do |nodoServiceA2|
    nodoServiceA2.vm.box = "centos_rabbit"
    nodoServiceA2.vm.network :private_network, ip: "192.168.56.64"
    nodoServiceA2.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "256","--cpus", "1", "--name", "centos_serviceA2" ]
    end
    nodoServiceA2.vm.provision "shell", path: "serviceA.sh"
  end
end


